### ISSUE TITLE
Validating multiple files fails after the first

### ISSUE THREAD

**Issue by misterflippy** [prantlf/gulp-jsonlint#2]
Validating multiple files results in an error for all files after the first. This occurs whether the first file validated successfully or not.

Error message: "finish is not a function"

The code I'm using is as follows:
```
    return src('test-files/*.json')
        .pipe(through.obj(outputFilename))
        .pipe(jsonlint({
            schema: {
                src: "test.schema.json"
            }
        }))
        .pipe(jsonlint.reporter())
        .pipe(jsonlint.failAfterError())
```

Example files: [gulp-jsonlint-test.zip](https://github.com/prantlf/gulp-jsonlint/files/3356399/gulp-jsonlint-test.zip)

**Comment by prantlf** [comment]
Thanks for the report and the suggested fix, @misterflippy! A stupid mistake of mine, sorry.

I pulled your change and released it in the version [2.3.0](https://github.com/prantlf/gulp-jsonlint/releases/tag/v2.3.0).
