### ISSUE TITLE
Validation - subsequent files fail after first failure when using custom parser

### ISSUE THREAD

**Issue by misterflippy** [prantlf/gulp-jsonlint#4]
When using validation and options that require a custom parser (e.g. ignoreComments or ignoreTrailingCommas), all files fail validation once any file has failed.

The files fail with error:
```
/ should be object; see #/type
```

This appears to be due to:
* gulp-jsonlint uses a single options object (parserOptions) for all operations
* jsonlint.tokenize sets `options.tokenize = true` when an error occurs
* options.tokenize persists to the next file since the object is shared for all operations
* jsonlint.parse returns a tokenized object instead of a json object and ajv fails to process the tokenized object

Example (run `npm run test`): [gulp-jsonlint-test_tokenize.zip](https://github.com/prantlf/gulp-jsonlint/files/3357909/gulp-jsonlint-test_tokenize.zip)

**Comment by prantlf** [comment]
Thank you for the perfect analysis, @misterflippy!

It is rather nasty behaviour of the `tokenize` method. Input option objects can be shared and modifying them in the called function is unexpected. And even in a way, which changes the output of the called options.

I decided to [fix the `tokenize` method in jsonlint](https://github.com/prantlf/jsonlint/commit/7e3ac0babf873c42da1daadaee2bbe55d2644690) not to modify the input options. I am sorry for not pulling your code change, which would be the right fix, when the dependant module could not be changed. Thanks again!

I released the upgrade to the fixed [`@prantlf/jsonlint` 10.0.2](https://github.com/prantlf/jsonlint/releases/tag/v10.0.2) in the version [2.3.0](https://github.com/prantlf/gulp-jsonlint/releases/tag/v2.3.0).
